version: "3.9"

services:
  keycloakdb:
    container_name: asp-react-auth-keycloakdb
    image: postgres:12.9
    volumes:
      - keycloakdb:/var/lib/postgresql/data
    ports:
      - 52432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h keycloakdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - asp-react-auth-network

  keycloak:
    container_name: asp-react-auth-keycloak
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: PdZoV9NpYuq#zdsYXfHo
      KC_FEATURES:
        token-exchange
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_CACHE_STACK: tcp
    volumes:
      - ./.keycloak:/opt/keycloak/data/import/:ro
    command:
      - "start"
      - "--http-port 52433"
      - "--proxy=passthrough"
      - "--import-realm"
    ports:
      - 52433:52433
    depends_on:
      - keycloakdb
    networks:
      asp-react-auth-network:
        ipv4_address: 172.18.0.3
    
  web:
    image: node:14.17.6-alpine
    container_name: asp-react-auth-web
    stdin_open: true
    deploy:
      replicas: 1
    ports:
      - "52434:52434"
    volumes:
      - "$PWD/src/react:/app:rw"
    depends_on:
      - keycloak
    environment:
      REACT_APP_ENVIRONMENT_NAME: development
      NODE_ENV: development
      PORT: 52434
      REACT_APP_KEYCLOAK_URL: http://172.18.0.3:52433/realms/react-example
      REACT_APP_KEYCLOAK_REALM: react-example
      REACT_APP_KEYCLOAK_CLIENT_ID: react
      REACT_APP_KEYCLOAK_REDIRECT_URL: http://localhost:52434/
      REACT_APP_BACKEND_URL: http://localhost:52435
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    networks:
      - asp-react-auth-network

  backend:
    build: ./src/backend
    container_name: asp-react-auth-backend
    deploy:
      replicas: 1
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_ENVIRONMENT: Development
    depends_on:
      - keycloak
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    ports:
      - "52435:80"
    networks:
      - asp-react-auth-network

networks:
  asp-react-auth-network:
    name: asp-react-auth-network
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"

volumes:
  keycloakdb:
    driver: local